# -*- coding: utf-8 -*-
"""lab2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16wEEJe3lb2zJoc1TPynAkuIWTHeJR49k
"""

!apt-get install openjdk-8-jdk-headless -qq > /dev/null
!wget -q https://downloads.apache.org/spark/spark-3.5.1/spark-3.5.1-bin-hadoop3.tgz
!tar xf spark-3.5.1-bin-hadoop3.tgz
!pip install -q findspark

import os, sys

os.environ["JAVA_HOME"]             = r"C:\Program Files\Java\jdk-19"
os.environ["PATH"]                  = os.environ["JAVA_HOME"] + r"\bin;" + os.environ["PATH"]
os.environ["PYSPARK_PYTHON"]        = sys.executable
os.environ["PYSPARK_DRIVER_PYTHON"] = sys.executable

from pyspark.sql import SparkSession
spark = SparkSession.builder.appName("Lab2").master("local[*]").getOrCreate()
sc = spark.sparkContext
sc.setLogLevel("ERROR")

print("Python:", sys.version)
print("PySpark:", spark.version)

"""# PHASE 1: Data Loading & Inspection

"""

# Create Spark session and context
spark = SparkSession.builder \
    .appName("Lab2_Telco_Churn") \
    .master("local[*]") \
    .getOrCreate()
sc = spark.sparkContext

# Load dataset using sc.textFile()
raw_rdd = sc.textFile("dataset.csv")
raw_rdd.cache()

header = raw_rdd.first()
data_rdd = raw_rdd.filter(lambda line: line != header)

# Split rows into columns using map()
split_rdd = data_rdd.map(lambda line: line.split(",")).cache()

# Display sample records using take()
print("\nSample Records (first 3 rows):")
for record in split_rdd.take(3):
    print(record)

# Count total records using count()
total_records = split_rdd.count()
print(f"\nTotal Records: {total_records}")

# Count number of partitions using getNumPartitions()
num_partitions = split_rdd.getNumPartitions()
print(f"Number of Partitions: {num_partitions}")

print("\nColumn Names:")
print(header.split(","))

"""# PHASE 2: Data Cleaning (RDD transformations only)"""

NUM_COLS = len(header.split(","))

# Step 1: Trim whitespace from all fields using map()
trimmed_rdd = split_rdd.map(lambda row: [field.strip() for field in row]).cache()

# Step 2: Fix malformed rows - keep only rows with correct number of columns using filter()
fixed_rdd = trimmed_rdd.filter(lambda row: len(row) == NUM_COLS).cache()
print(f"\nAfter fixing malformed rows: {fixed_rdd.count()} records")

# Step 3: Remove rows with missing/empty values using filter()
no_missing_rdd = fixed_rdd.filter(
    lambda row: all(field != "" and field.strip() != " " for field in row)
).cache()
print(f"After removing missing values: {no_missing_rdd.count()} records")

# Step 4: Remove duplicate records using distinct()
# بدل distinct() عادي، نستخدم reduceByKey كبديل أخف
no_duplicates_rdd = no_missing_rdd \
    .map(lambda row: (row[0], row)) \
    .reduceByKey(lambda a, b: a) \
    .map(lambda kv: kv[1]) \
    .cache()

print(f"After removing duplicates: {no_duplicates_rdd.count()} records")

# Step 5: Convert numeric columns to proper types using map()
# Columns by index (0-based):
#   5  = tenure (int)
#   18 = MonthlyCharges (float)
#   19 = TotalCharges (float)

def convert_types(row):
    try:
        row[5]  = int(row[5])           # tenure
        row[18] = float(row[18])         # MonthlyCharges
        row[19] = float(row[19]) if row[19] not in ("", " ") else 0.0  # TotalCharges
        return row
    except (ValueError, IndexError):
        return None  # mark bad rows for removal

typed_rdd = no_duplicates_rdd.map(convert_types)

# Remove rows that failed type conversion
clean_rdd = typed_rdd.filter(lambda row: row is not None)
print(f"After type conversion & final cleanup: {clean_rdd.count()} records")

print("\nSample cleaned record:")
print(clean_rdd.take(1))

"""# PHASE 3: Core RDD Transformations"""

# --- 1. map() ---
# Purpose: Transform each row to extract (customerID, MonthlyCharges) tuple
customer_charges = clean_rdd.map(lambda row: (row[0], row[18]))
print("\n1. map() - Extract (customerID, MonthlyCharges):")
print(customer_charges.take(3))

# --- 2. filter() ---
# Purpose: Keep only customers with Fiber optic internet service (index 8 = InternetService)
fiber_customers = clean_rdd.filter(lambda row: row[8] == "Fiber optic")
print(f"\n2. filter() - Fiber optic customers count: {fiber_customers.count()}")
print(fiber_customers.take(2))

# --- 3. flatMap() ---
# Purpose: Extract all unique service features each customer has (Yes values)
# Columns 6-14 are service-related; get feature name for each "Yes"
service_cols = ["PhoneService", "MultipleLines", "InternetService",
                "OnlineSecurity", "OnlineBackup", "DeviceProtection",
                "TechSupport", "StreamingTV", "StreamingMovies"]

customer_services = clean_rdd.flatMap(
    lambda row: [(row[0], service_cols[i]) for i, col_idx in
                 enumerate(range(6, 15)) if row[col_idx] == "Yes"]
)
print(f"\n3. flatMap() - (customerID, service) pairs count: {customer_services.count()}")
print("Sample:", customer_services.take(4))

# --- 4. distinct() ---
# Purpose: Get all unique contract types (index 16 = Contract)
contract_types = clean_rdd.map(lambda row: row[16]).distinct()
print(f"\n4. distinct() - Unique contract types: {contract_types.collect()}")

# --- 5. sample() ---
# Purpose: Take a random 10% sample for exploratory analysis
sampled_rdd = clean_rdd.sample(withReplacement=False, fraction=0.1, seed=42)
print(f"\n5. sample() - 10% sample size: {sampled_rdd.count()} records")

# --- 6. mapPartitions() ---
# Purpose: Count rows per partition for load distribution analysis
def count_in_partition(iterator):
    count = sum(1 for _ in iterator)
    yield count

partition_counts = clean_rdd.mapPartitions(count_in_partition)
print(f"\n6. mapPartitions() - Records per partition: {partition_counts.collect()}")

# --- 7. repartition() ---
# Purpose: Increase parallelism by repartitioning into 4 partitions
repartitioned_rdd = clean_rdd.repartition(4)
print(f"\n7. repartition() - New partition count: {repartitioned_rdd.getNumPartitions()}")

# --- 8. coalesce() ---
# Purpose: Reduce partitions to 2 without full shuffle (efficient for writing output)
coalesced_rdd = clean_rdd.coalesce(2)
print(f"\n8. coalesce() - Coalesced partition count: {coalesced_rdd.getNumPartitions()}")

"""# PHASE 4: Key-Value Operations"""

# Prepare key-value RDD: key = Contract type, value = MonthlyCharges
# Index 16 = Contract, Index 18 = MonthlyCharges
contract_charges_rdd = clean_rdd.map(lambda row: (row[16], row[18]))

# Index 20 = Churn, key-value for churn analysis
churn_rdd = clean_rdd.map(lambda row: (row[20], 1))

# --- 1. reduceByKey() ---
# Purpose: Sum MonthlyCharges per Contract type
total_charges_by_contract = contract_charges_rdd.reduceByKey(lambda a, b: a + b)
print("\n1. reduceByKey() - Total MonthlyCharges per Contract type:")
for item in total_charges_by_contract.collect():
    print(f"   {item[0]}: ${item[1]:,.2f}")

# --- 2. groupByKey() ---
# Purpose: Group customers by gender (index 1 = gender)
gender_rdd = clean_rdd.map(lambda row: (row[1], row[0]))  # (gender, customerID)
grouped_by_gender = gender_rdd.groupByKey()
print("\n2. groupByKey() - Customer counts grouped by gender:")
for gender, customers in grouped_by_gender.collect():
    print(f"   {gender}: {len(list(customers))} customers")

# --- 3. countByKey() ---
# Purpose: Count number of customers per Churn status
churn_counts = churn_rdd.countByKey()
print("\n3. countByKey() - Customer count by Churn status:")
for status, count in churn_counts.items():
    print(f"   Churn={status}: {count} customers")

# --- 4. sortByKey() ---
# Purpose: Sort contract types alphabetically
sorted_contracts = total_charges_by_contract.sortByKey(ascending=True)
print("\n4. sortByKey() - Contract types sorted alphabetically:")
for item in sorted_contracts.collect():
    print(f"   {item[0]}: ${item[1]:,.2f}")

# --- 5. aggregateByKey() ---
# Purpose: Compute (min, max, sum, count) of MonthlyCharges per Contract type
# Zero value: (min=inf, max=-inf, sum=0, count=0)
zero_value = (float("inf"), float("-inf"), 0.0, 0)

def seq_func(acc, value):
    return (min(acc[0], value), max(acc[1], value), acc[2] + value, acc[3] + 1)

def comb_func(acc1, acc2):
    return (min(acc1[0], acc2[0]), max(acc1[1], acc2[1]),
            acc1[2] + acc2[2], acc1[3] + acc2[3])

agg_result = contract_charges_rdd.aggregateByKey(zero_value, seq_func, comb_func)
print("\n5. aggregateByKey() - MonthlyCharges stats (min, max, sum, count) per Contract:")
for contract, (mn, mx, sm, cnt) in agg_result.collect():
    avg = sm / cnt if cnt > 0 else 0
    print(f"   {contract}: min=${mn:.2f}, max=${mx:.2f}, avg=${avg:.2f}, count={cnt}")

# --- 6. combineByKey() ---
# Purpose: Compute average TotalCharges per Internet service type
# Index 8 = InternetService, Index 19 = TotalCharges
internet_charges_rdd = clean_rdd.map(lambda row: (row[8], row[19]))

create_combiner = lambda v: (v, 1)
merge_value     = lambda acc, v: (acc[0] + v, acc[1] + 1)
merge_combiners = lambda acc1, acc2: (acc1[0] + acc2[0], acc1[1] + acc2[1])

combined = internet_charges_rdd.combineByKey(create_combiner, merge_value, merge_combiners)
avg_charges_by_internet = combined.map(lambda kv: (kv[0], kv[1][0] / kv[1][1]))

print("\n6. combineByKey() - Avg TotalCharges per Internet Service type:")
for service, avg in avg_charges_by_internet.collect():
    print(f"   {service}: ${avg:,.2f}")

"""# PHASE 5: Partitioning & Performance"""

import time
# --- Analyze current partitions ---
print(f"\nInitial partition count (after cleaning): {clean_rdd.getNumPartitions()}")

# --- Execution WITHOUT caching ---
start = time.time()
_ = clean_rdd.filter(lambda r: r[20] == "Yes").count()
_ = clean_rdd.map(lambda r: r[18]).reduce(lambda a, b: a + b)
_ = clean_rdd.map(lambda r: (r[16], 1)).reduceByKey(lambda a, b: a + b).collect()
time_no_cache = time.time() - start
print(f"\nExecution time WITHOUT cache (3 actions): {time_no_cache:.4f} seconds")

# --- Cache the RDD ---
cached_rdd = clean_rdd.cache()
# Warm up the cache with one action
cached_rdd.count()

# --- Execution WITH caching ---
start = time.time()
_ = cached_rdd.filter(lambda r: r[20] == "Yes").count()
_ = cached_rdd.map(lambda r: r[18]).reduce(lambda a, b: a + b)
_ = cached_rdd.map(lambda r: (r[16], 1)).reduceByKey(lambda a, b: a + b).collect()
time_with_cache = time.time() - start
print(f"Execution time WITH cache    (3 actions): {time_with_cache:.4f} seconds")

speedup = time_no_cache / time_with_cache if time_with_cache > 0 else float("inf")
print(f"Speedup factor: {speedup:.2f}x")

# --- Repartition for parallelism ---
rdd_4p = clean_rdd.repartition(4)
print(f"\nAfter repartition(4): {rdd_4p.getNumPartitions()} partitions")

rdd_2p = rdd_4p.coalesce(2)
print(f"After coalesce(2):    {rdd_2p.getNumPartitions()} partitions")

# --- Performance Discussion ---
print("""
Performance Observations:
-------------------------------------------------
1. Partitions:
   - Default partitions depend on HDFS block size or local parallelism.
   - repartition() triggers a full shuffle (expensive but balances data).
   - coalesce() merges partitions without a full shuffle (efficient for shrinking).

2. Caching (cache / persist):
   - cache() stores the RDD in memory after the first action.
   - Subsequent actions reuse the cached data, avoiding recomputation.
   - Speedup is most noticeable when the same RDD is used in multiple actions.
   - Use persist(StorageLevel.MEMORY_AND_DISK) if data doesn't fit in memory.

3. General Tips:
   - Avoid groupByKey() for aggregations — use reduceByKey() or aggregateByKey()
     instead, as they reduce data transferred across the network.
   - Keep partitions balanced: too few → underutilizes cores;
     too many → overhead from task scheduling.
""")

# Stop Spark context
sc.stop()
print("Spark context stopped. Lab 2 complete.")